# Change these first
owner: blinkergit # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Violet Prod
    url: https://violet.blinker-prod.com
  - name: Violet Stage
    url: https://violet.blinker-stage.com
  - name: Violet Dev
    url: https://violet.blinker-dev.com

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Blinker Uptime
  introTitle: Uptime stats for Blinker
  introMessage: Uptime stats for Blinker
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
